name: PVPPlugin
main: samoth69.plugin.PVPPluginMain
version: 1.0
load: POSTWORLD
commands:
  pvp:
    description: pvp plugin command. type '/pvp help' for more info
    usage: /pvp help
  t:
    description: utilise cette commande pour communiquer avec les taupes
    usage: /t message
  claim:
    description: permet d'obtenir un kit spécial pour les taupes
    usage: /claim
depend: [TitleAPI, ActionBarAPI, ProtocolLib, PacketWrapper]
